packages:
  - apps/*
  - packages/*

autoInstallPeers: false
engineStrict: true
peerDependencyRules:
  ignoreMissing:
    - '@daveyplate/better-auth-tanstack'
    - '@instantdb/react'
    - '@tanstack/react-query'
    - '@triplit/client'
    - '@triplit/react'
saveExact: true
sharedWorkspaceLockfile: true
strictPeerDependencies: true
verifyStoreIntegrity: true
